---
name: Build
on:
  push:
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build Go
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Go 1.23
        uses: actions/setup-go@v4
        with:
          go-version: ^1.23
      - name: Build Go
        run: make build
